### PR TITLE
Release 8

### PR DESCRIPTION
**Pull request by bekozi**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bekozi** [comment]
@ocefpaf Do you understand the error with osx builds? There is very little debug output to work from.

**Comment by ocefpaf** [comment]
> @ocefpaf Do you understand the error with osx builds? There is very little debug output to work from.

Not sure. It may be related to `mpi` but I don't have a macOS to test it.

**Comment by ocefpaf** [comment]
Looking at the `esmf` logs seems that we pull hdf5 nompi but we do install mpich :-/

**Comment by bekozi** [comment]
> Looking at the `esmf` logs seems that we pull hdf5 nompi but we do install mpich :-/

Do you think we need to switch to an hdf5 mpi installation? I'm surprised this is showing up in python first and osx only. I'm going to try removing anything interesting from `run_test.py` to see if the failure is in esmpy code.

**Comment by bekozi** [comment]
The build log error is: 
```
./conda_test_runner.sh: line 2:  7955 Illegal instruction: 4  "./bin/python" -s "./test_tmp/run_test.py"
```
[SO indicates](https://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10) this could be a problem on osx with module optimizations. In which case, we may need to rebuild esmf without optimizations on.

**Comment by ocefpaf** [comment]
> Not sure who added the run_test.py file as it would never work in parallel without importing mpi4py.

Maybe I did that. I don't recall. I'll rebase this tomorrow and try to get it fixed. Thanks!

**Comment by ocefpaf** [comment]
I cannot push to your branch @bekozi :-(

**Comment by bekozi** [comment]
> I cannot push to your branch @bekozi :-(

That's okay. I'll modify the test for the serial environment. Thanks for giving it a try. I don't think it would be run in parallel ever anyway.

Also not sure why you can't push. Do you need to have special permissions on the fork or something? I allowed edits from maintainers.

**Comment by bekozi** [comment]
I'm closing this and trying again on a new branch...

**Pull request closed without merging**
