### PR TITLE
enable `noarch` or `arm64`

### PR DESCRIPTION
**Pull request by aaronspring**
for apple silicon arm64

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by aaronspring** [comment]
probably noarch doesnt work, but I'd like to add `arm64` https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocessing-selectors

**Comment by aaronspring** [comment]
try https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2452 following https://conda-forge.org/docs/maintainer/knowledge_base.html#apple-silicon-builds

**Comment by xylar** [comment]
@aaronspring, you will need to rerender for these changes to be noticed and the build to occur properly.

However, I don't think you can use `noarch: python` in combination with various MPI versions.  I could be wrong but I'm not aware of any repo that does this.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
A reason this feedstock hasn't been built for `arm64` is that ESMF has not been built yet for those architectures: https://github.com/conda-forge/esmf-feedstock/tree/master/.ci_support.  I'm not sure why not.  It seems it is just getting skipped by the migration bot: https://conda-forge.org/status/#other_migrations.

I can look into it.  But making this package `noarch` isn't going to help you.

**Comment by aaronspring** [comment]
> can look into it. But making this package noarch isn't going to help you.

Thanks for the explanation. So I better close this PR?

**Comment by xylar** [comment]
Yes, I'm afraid so.  But it was an important thing for you to point out that we're missing.  I will try to work on it over the weekend, but it might be quite a bit over my head if I run into trouble with ESMF.

**Pull request closed without merging**
