### PR TITLE
801release

### PR DESCRIPTION
**Pull request by rokuingh**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rokuingh** [comment]
ESMF is migrating to github, and the final location of the source download has not yet been decided, will update when available.

**Comment by rokuingh** [comment]
From what I can tell, these checks are not passing because the 801 version of esmf is not yet available, due to pending [pr](https://github.com/conda-forge/esmf-feedstock/pull/55)

**Comment by xylar** [comment]
Thanks again @rokuingh. We can restart the CI once the new `esmf` packages have been up for an hour or so.

**Comment by xylar** [comment]
@conda-forge-admin, please restart ci

**Pull request merged**
