### PR TITLE
Add MPI build matrix

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
Testing will most likely fail until https://github.com/conda-forge/esmf-feedstock/pull/47 is merged.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@bekozi, @rokuingh and @ocefpaf, I'm headed to bed.  If the tests pass, I think this is ready to merge as far as I'm concerned.  Let me know what you think.

**Comment by ocefpaf** [comment]
Amazing work with the `mpi` stuff @xylar! Thanks for doing this!

**Comment by xylar** [comment]
@ocefpaf, thanks very much for your help along the way.  It's been a learning experience.  I imagine there will be some unintended consequences along the way but overall I hope this gives the community more options.  It'll certainly help me with keeping the tools I use compatible with one another in environments with MPI.

I think we're going to have to start telling users how to install the intended versions of packages, though.  I would have guessed that it would be enough to just install `mpich` or `openmpi` and then you would get the appropriate version of all the libs and packages.  Not so, you need to supply the funky `<package>=*=mpi_mpich*` syntax on at least one package or you typically get the `nompi` version.

**Comment by ocefpaf** [comment]
> @ocefpaf, thanks very much for your help along the way.

All I did was to hit the merge button ;-p

> It's been a learning experience.

No pressure, but if you think it is worth it, can you write some notes/docs about your experience with this? No one else has done so many multiple outputs with mpi as you did.

> I imagine there will be some unintended consequences along the way but overall I hope this gives the community more options. It'll certainly help me with keeping the tools I use compatible with one another in environments with MPI.

Don't worry about that. It is "part of the job."

> I think we're going to have to start telling users how to install the intended versions of packages, though. I would have guessed that it would be enough to just install `mpich` or `openmpi` and then you would get the appropriate version of all the libs and packages. Not so, you need to supply the funky `<package>=*=mpi_mpich*` syntax on at least one package or you typically get the `nompi` version.

Indeed that is a flaw IMO. I believe there is an issue upstream in `conda` about it.

**Comment by xylar** [comment]
> > It's been a learning experience.

> No pressure, but if you think it is worth it, can you write some notes/docs about your experience with this? No one else has done so many multiple outputs with mpi as you did.

Oh, I don't think there's a ton to learn for the community in general, just what I had to learn that I wasn't aware of, like how packages need to be listed twice (once for conda-smithy and once for the build pinning and various things specific to how different packages interact with MPI compilers that cause trouble).  If I think of some notes that would be useful in a more general sense, I'll pass them along, though.

> Indeed that is a flaw IMO. I believe there is an issue upstream in conda about it.

Yeah, I tend to agree.  I'll keep an eye on discussions upstream, then, and see what kinds of workaround seem reasonable for my projects in the meantime.

**Pull request merged**
