### PR TITLE
esmpy v8.4.1 noarch: python

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #69

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@zklaus, @ocefpaf and @rokuingh, I think this is working (though we won't know if it works for non-linux-64 architectures until we build a package).

I can confirm that `mpi4py` is optional:
https://github.com/esmf-org/esmf/blob/v8.4.1/src/addon/esmpy/doc/install.rst

It also seems that one can install with `esmf * nompi_*` and test just fine with `esmf * mpi_mpich_*` so I think MPI isn't going to give us trouble.

As part of installation, we run the serial tests, and in the `test` phase we run MPI tests so I'm feeling like testing is about as thorough as it can reasonably be on on architecture.

Please let me know what you think.

**Comment by billsacks** [comment]
As you have found, @rokuingh 's availability is very limited right now. And, unfortunately, the ESMF team as a whole is currently at a reduced size; we are hoping to build it back up somewhat in the near future. I am trying to fill in for @rokuingh on critical ESMPy issues as part of my half-time work on ESMF, but I'm still very much in a learning phase myself. You can add me as a maintainer in order to keep me in the loop and act as a liaison between this community and the ESMF core team, but I can't promise a lot of time to this right now.

Regarding the `noarch: python` build: I don't know enough about this to give you a definite answer, and I think the same is true of others on the ESMF team. I'd say that, if it's passing your tests, then let's go ahead with it.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@billsacks, we're all volunteers here so there's certainly no expectation of any time commitment.  I've added you as a maintainer.  We'll go ahead and give this a shot.  @zklaus seems confident that this should work as expected and I trust his judgment.

**Pull request merged**
